spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver